moviename/movieapp/urls.py
from django.urls import path, include
from . import views
app_name = 'movieapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.details, name='details'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

moviename/moviename/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviename/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

moviename/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

moviename/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Movie
from .forms import MovieForm


# Create your views here.


def index(request):
    movie = Movie.objects.all()
    context = {
        'movielist': movie
    }
    return render(request, 'index.html', context)


def details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

moviename/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token%}
  <input type="text" name="name" placeholder="Place name"><br>
  <input type="text" name="desc" placeholder="Description"><br>
  <input type="text" name="year" placeholder="Rating"><br>
  <input type="file" name="img" ><br>
  <input type="submit" ><br>
</form>

{% endblock %}

moviename/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
   Travel Places
  </a>
    <form class="d-flex" action="{% url 'movieapp:add_movie' %}" method="get">
        <button class="btn btn-outline-success" type="submit">Add Movie</button>
    </form>
</nav>
{% block body %}
{% endblock %}


</body>
</html>

moviename/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
  {% csrf_token %}
  Are you sure to delete this Place:
  <input type="submit">
</form>
{% endblock %}

moviename/templates/details.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h4>{{movie.desc}}</h4>
            <h4>{{movie.year}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

moviename/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock %}

moviename/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        {% for i in movielist %}
        <div class="col-md-4">
            <div class="card" style="width: 20rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100" height="250">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:details' i.id %}"" class="btn btn-primary">Details</a>
                </div>
            </div>
            <br>
        </div>
        {% endfor %}
    </div>
</div>






{% endblock %}